namespace Simpiens.Cognition.Contracts
{
    /// <summary>
    /// Base class for all agent intents. Intents are generated by the cognitive evaluator
    /// in the background and executed on the main thread by the SimulationManager.
    /// </summary>
    public abstract class AgentIntent
    {
        public readonly UnityEngine.GUID AgentId;
        public System.Action OnComplete { get; set; }

        protected AgentIntent(UnityEngine.GUID agentId)
        {
            AgentId = agentId;
        }
    }
}
